# fly.toml app configuration file generated for asu-ai-api on 2024-02-01T20:59:25-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'asu-ai-api'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
